# https://travis-ci.org/tornadoweb/tornado
language: python
python:
    - 2.7

install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt

script:
    - python manage.py test

deploy:
    provider: script
    script: deploy/deploy-native.sh
    on:
        branch: develop

