FROM python:3.6.0-slim

COPY requirements.txt \
     test-requirements.txt \
     /tmp/

RUN apt-get update \
 && apt-get install -y libtiff5-dev libjpeg62-turbo-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk \
 && pip3 install --no-cache-dir -r /tmp/requirements.txt

COPY ./ ${PJK_HOME}/src/

WORKDIR ${PJK_HOME}/src
CMD ["python3", "manage.py", "migrate"]
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8080"]
