# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('min', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goal', models.IntegerField()),
                ('away_goal', models.IntegerField()),
                ('home_goal_first', models.IntegerField()),
                ('away_goal_first', models.IntegerField()),
                ('technical', models.BooleanField(default=None)),
                ('date_time', models.DateTimeField()),
                ('hasResult', models.BooleanField(default=False)),
                ('register', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=70)),
                ('lastName', models.CharField(max_length=70)),
                ('birth', models.DateField()),
                ('vk_link', models.CharField(max_length=30, null=True)),
                ('basePosition', models.CharField(max_length=1)),
                ('image', models.ImageField(upload_to=b'media')),
            ],
        ),
        migrations.CreateModel(
            name='RecOfTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField(default=-1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('accr', models.BooleanField(default=True)),
                ('description', models.TextField(default=b'olo')),
                ('estimate', models.FloatField()),
                ('physics', models.IntegerField()),
                ('image', models.ImageField(default=b'/media/404/', upload_to=b'media')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('foundation', models.IntegerField()),
                ('image', models.ImageField(upload_to=b'media')),
                ('vk_link', models.CharField(default=b'nulls', max_length=30, null=True)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teamlogic.Player')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Stadium')),
                ('players', models.ManyToManyField(through='teamlogic.RecOfTeam', to='teamlogic.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_s', models.IntegerField()),
                ('goal_p', models.IntegerField()),
                ('match_v', models.IntegerField()),
                ('match_n', models.IntegerField()),
                ('match_p', models.IntegerField()),
                ('penalty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(upload_to=b'')),
                ('members', models.ManyToManyField(through='teamlogic.TeamInLeague', to='teamlogic.Team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchInLeague',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teamlogic.Match')),
                ('tour', models.IntegerField(default=2)),
            ],
            bases=('teamlogic.match',),
        ),
        migrations.AddField(
            model_name='teaminleague',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Tournament'),
        ),
        migrations.AddField(
            model_name='teaminleague',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Team'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='home',
            field=models.ManyToManyField(blank=True, null=True, to='teamlogic.Team'),
        ),
        migrations.AddField(
            model_name='recofteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='history',
            field=models.ManyToManyField(null=True, through='teamlogic.RecOfTeam', to='teamlogic.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teamlogic.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_goals',
            field=models.ManyToManyField(related_name='away', to='teamlogic.Goal'),
        ),
        migrations.AddField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teamlogic.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_goals',
            field=models.ManyToManyField(related_name='home', to='teamlogic.Goal'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Stadium'),
        ),
        migrations.AddField(
            model_name='manager',
            name='tournaments',
            field=models.ManyToManyField(to='teamlogic.Tournament'),
        ),
        migrations.AddField(
            model_name='goal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='matchs',
            field=models.ManyToManyField(to='teamlogic.MatchInLeague'),
        ),
    ]
