# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='history',
            field=models.ManyToManyField(through='teamlogic.RecOfTeam', to='teamlogic.Team'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='home',
            field=models.ManyToManyField(to='teamlogic.Team'),
        ),
    ]
