# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teamlogic.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'media'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vk_link',
            field=models.CharField(blank=True, default=b'nulls', max_length=30, null=True),
        ),
    ]
