# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0002_auto_20160826_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Stadium'),
        ),
    ]
