# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0002_auto_20170102_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='description',
            field=models.TextField(default='olo'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='home',
            field=models.ManyToManyField(blank=True, null=True, to='teamlogic.Team'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='image',
            field=models.ImageField(default='/media/404/', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vk_link',
            field=models.CharField(blank=True, default='nulls', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
