# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0003_auto_20160826_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminleague',
            name='straf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teaminleague',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
