# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0003_auto_20170316_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.ManyToManyField(blank=True, null=True, related_name='away', to='teamlogic.Goal'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.ManyToManyField(blank=True, null=True, related_name='home', to='teamlogic.Goal'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
