# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0004_auto_20170317_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchinleague',
            old_name='tour',
            new_name='tour1',
        ),
        migrations.AddField(
            model_name='match',
            name='tour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
