# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0006_timeboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
