# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0007_match_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeboard',
            name='time1',
        ),
        migrations.AddField(
            model_name='timeboard',
            name='time1',
            field=models.IntegerField()
        ),
        migrations.RemoveField(
            model_name='timeboard',
            name='time2'
        ),
        migrations.AddField(
            model_name='timeboard',
            name='time2',
            field=models.IntegerField()
        )
    ]
