# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0008_auto_20170318_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='image',
            field=models.ImageField(default=b'./404/stadion.jpg', upload_to=b'media'),
        ),
    ]
