# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0010_auto_20170618_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default=b'./404/team.jpg', null=True, upload_to=b'media'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, default=b'./404/tournament.jpg', null=True, upload_to=b''),
        ),
    ]
