# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0011_auto_20170618_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='recofteam',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default=b'./404/team.jpg', null=True, upload_to=b'./teams'),
        ),
    ]
