# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0014_auto_20170622_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='members2',
            field=models.ManyToManyField(blank=True, null=True, related_name='members2', to='teamlogic.Team'),
        ),
    ]
