# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0015_tournament_members2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goal',
            field=models.IntegerField(default=0),
        ),
    ]
