# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0016_auto_20170712_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, default=b'./404/tournament.jpg', null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamlogic.Cup')),
                ('first_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_match', to='teamlogic.Match')),
                ('previous_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamlogic.MatchPair')),
                ('second_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_match', to='teamlogic.Match')),
            ],
        ),
    ]
