# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0017_cup_matchpair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cup',
            options={'verbose_name': '\u041a\u0443\u0431\u043e\u043a', 'verbose_name_plural': '\u041a\u0443\u0431\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': '\u0413\u043e\u043b', 'verbose_name_plural': '\u0413\u043e\u043b\u044b'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': '\u041c\u0430\u0442\u0447', 'verbose_name_plural': '\u041c\u0430\u0442\u0447\u0438'},
        ),
        migrations.AlterModelOptions(
            name='matchpair',
            options={'verbose_name': '\u041f\u0430\u0440\u0430 \u043c\u0430\u0442\u0447\u0435\u0439', 'verbose_name_plural': '\u041f\u0430\u0440\u044b \u043c\u0430\u0442\u0447\u0435\u0439'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': '\u0418\u0433\u0440\u043e\u043a', 'verbose_name_plural': '\u0418\u0433\u0440\u043e\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'verbose_name': '\u0421\u0442\u0430\u0434\u0438\u043e\u043d', 'verbose_name_plural': '\u0421\u0442\u0430\u0434\u0438\u043e\u043d\u044b'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u0430', 'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': '\u0427\u0435\u043c\u043f\u0438\u043e\u043d\u0430\u0442', 'verbose_name_plural': '\u0427\u0435\u043c\u043f\u0438\u043e\u043d\u0430\u0442\u044b'},
        ),
        migrations.AddField(
            model_name='matchpair',
            name='only_one_match',
            field=models.BooleanField(default=False),
        ),
    ]
