# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-22 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0019_auto_20170721_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchpair',
            old_name='previous_pair',
            new_name='next_pair',
        ),
    ]
