# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-02 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamlogic', '0021_auto_20171125_1122'),
        ('teamlogic', '0021_auto_20171112_1639'),
    ]

    operations = [
    ]
