# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to=b'media')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(default=b'')),
                ('content', models.TextField()),
                ('pubdate', models.DateTimeField()),
                ('image', models.ImageField(upload_to=b'media')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carusele.News'),
        ),
    ]
